export const flagMap: Record<string, string> = {
  "brasil": "br",
  "argentina": "ar",
  "escócia": "gb-sct",
  "escocia": "gb-sct",
  "inglaterra": "gb-eng",
  "país de gales": "gb-wls",
  "pais de gales": "gb-wls",
  "alemanha": "de",
  "espanha": "es",
  "frança": "fr",
  "franca": "fr",
  "itália": "it",
  "italia": "it",
  "portugal": "pt",
  "holanda": "nl",
  "bélgica": "be",
  "belgica": "be",
  "croácia": "hr",
  "croacia": "hr",
  "uruguai": "uy",
  "colômbia": "co",
  "colombia": "co",
  "chile": "cl",
  "equador": "ec",
  "peru": "pe",
  "paraguai": "py",
  "méxico": "mx",
  "mexico": "mx",
  "eua": "us",
  "estados unidos": "us",
  "japão": "jp",
  "japao": "jp",
  "coreia do sul": "kr",
  "marrocos": "ma",
  "senegal": "sn",
  "suécia": "se",
  "suecia": "se",
  "suíça": "ch",
  "suica": "ch",
  "polônia": "pl",
  "polonia": "pl",
  "dinamarca": "dk",
  "sérvia": "rs",
  "servia": "rs",
  "canadá": "ca",
  "canada": "ca",
  "austrália": "au",
  "australia": "au",
  "camarões": "cm",
  "camaroes": "cm",
  "gana": "gh",
  "tunísia": "tn",
  "tunisia": "tn",
  "arábia saudita": "sa",
  "arabia saudita": "sa",
  "irã": "ir",
  "ira": "ir",
  "catar": "qa"
};

export function getFlagUrl(teamName: string): string | undefined {
  if (!teamName) return undefined;
  const normalized = teamName.toLowerCase().trim();
  const code = flagMap[normalized];
  if (code) return `https://flagcdn.com/${code}.svg`;
  return undefined;
}
